# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbit" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "4858c1ffec4e7a36cb3d557bd3bb724ac1876c6aef5ee31b5b33738ab39f0f14"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed166be8e23efcd48cc95fdb06add425b04cfe7fcc3b7a4eff88f20f04a3807a"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82adbfff29278aba9c1c7496664021301599d6a1ac57626cd206ae1443b2e746"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e938171f6e1aa32b6fcb211c60d81880747a44ae74731c2f7075b12c07f909c0"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orbit"
  desc "Dashboard for the Claude Code, Codex and Copilot CLI sessions on your machine"
  homepage "https://github.com/SadriG91/orbit"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
    "tmux",
  ]

  binary "orbit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", "#{staged_path}/orbit"],
                     must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Config is written to ~/.config/orbit/ on first run (tmux.conf and config.toml); both are yours to edit. Opening a session in a new Ghostty tab needs Accessibility permission for your terminal — without it, press `i` to attach in the current one instead.
  EOS
end
