# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbit" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "cf617d3f7f4fd8a73d145fa0da930375508203e584d476d8d77eb9b9a391188a"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fd2bf083a72249957f182902153dd15c75524e4915705b9b66f03b65fb076e9"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d93add0205269fcdfdab7a0b439f77ab3549022994106ad01bc6bb51b9957243"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b5251617441dd4e058fa987a5d6196a0bdf7216b34e332cdbccde817af9241ec"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orbit"
  desc "Dashboard for the Claude Code, Codex and Copilot CLI sessions on your machine"
  homepage "https://github.com/SadriG91/orbit"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
    "tmux",
  ]

  binary "orbit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", "#{staged_path}/orbit"],
                     must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Config is written to ~/.config/orbit/ on first run (tmux.conf and config.toml); both are yours to edit. Opening a session in a new Ghostty tab needs Accessibility permission for your terminal — without it, press `i` to attach in the current one instead.
  EOS
end
