# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbit" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "78d682da7f7c23db677646d4ff0c623a236e80546f3f2310bffa9cf12de160aa"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d1ac0dbfd1f2b4e183889574128a34994e19051e9c95bc763aada901a544eb5"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "473e4871d0bbbba148212454d6d301c3892cdb6c20c104b91e8e97176774365f"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f038e2ca4e2f92fdc99852104e334eedc98a45f182a09575ee3f8bc6df1acb34"
      url "https://github.com/SadriG91/orbit/releases/download/v#{version}/orbit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orbit"
  desc "Dashboard for the Claude Code, Codex and Copilot CLI sessions on your machine"
  homepage "https://github.com/SadriG91/orbit"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
    "tmux",
  ]

  binary "orbit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", "#{staged_path}/orbit"],
                     must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Config is written to ~/.config/orbit/ on first run (tmux.conf and config.toml); both are yours to edit. Opening a session in a new Ghostty tab needs Accessibility permission for your terminal — without it, press `i` to attach in the current one instead.
  EOS
end
